### ISSUE TITLE
DOD OUD misdiagnosis - dict, step, and trig file updates

### ISSUE THREAD

**Issue by vilijajoyce** [suzytamang/clever-rockies#38]
**Background**
Jodie Trafton 8/20/24
_I may need your help to band-aid a OIG required program that we developed to ensure safe transitions of DOD patients treated for opioid use disorder to VHA care.  We are finding that a subset of the DOD patients were misdiagnosed and don't actually have opioid use disorder, but there is no way for us to tell if a provider assesses the patient and determines that they DON'T meet criteria.  That is getting them repeatedly prodded by the national case management program to ensure OIG compliance with a requirement to get the patients seen for the diagnosis in VA and offered harm reduction and treatment interventions.  Would it be much trouble to add a concept to your nightly NLP runs that would be a search for specific standard text (e.g. "Pt on DOD OUD report assessed. Pt does not meet criteria for opioid use disorder.") in clinical notes?  We could even share the patients that it could potentially be documented on if that would be helpful.  We would then use positives on that text search as exclusion criteria to remove patients from the case management program on the special report in STORM. Tolessa is already aware of the plan, if we can make the NLP side work.  If that is doable, I can finalize the exact text with the national case manager. I note that it isn't a lot of patients and the national care manager is in contact with their providers, so he can talk them through the documentation._

@suzytamang Please let me know if the following proposed fix would be appropriate. I'm somewhat worried that the modifiers might interfere w/ pulling these mentions. Please advise.
- [x] #39
`44000|DOD OUD report|DODOUD|report`
- [x] #41
  - Implement
  - Validate
- [x] #43
  - Implement
  - Validate
- [x] #45
  - Implement
  - Validate
- [x] #47
  - Implement
  - Validate
- [x] #49
- [x] #51

**Comment by suzytamang** [comment]
Hi Vilija,

This is similar to how the PDMP query works.

I'd suggest a new concept code such as "DODOUD", with a subclass value of "report".  It does not need any triggers so no need to create any entries as everything that is an exact match would be returned as "POSITIVE".

However, similar to what we did for Scott Ragland so that he could capture PDMP query results, whoever is requesting this needs to find the specific spans of templated text that we seek to match.  Each of these spans of templated text would get its own term ID.

I suggest that you let them know we need to have the terms by Monday, or whatever makes sense to make the deadline for the next release.

Suzanne
________________________________
From: Vilija Joyce ***@***.***>
Sent: Tuesday, August 20, 2024 17:07
To: suzytamang/clever-rockies ***@***.***>
Cc: Suzanne Tamang ***@***.***>; Mention ***@***.***>
Subject: [suzytamang/clever-rockies] DOD OUD misdiagnosis - dict, step, and trig file updates (Issue #38)


Background
Jodie Trafton 8/20/24
I may need your help to band-aid a OIG required program that we developed to ensure safe transitions of DOD patients treated for opioid use disorder to VHA care. We are finding that a subset of the DOD patients were misdiagnosed and don't actually have opioid use disorder, but there is no way for us to tell if a provider assesses the patient and determines that they DON'T meet criteria. That is getting them repeatedly prodded by the national case management program to ensure OIG compliance with a requirement to get the patients seen for the diagnosis in VA and offered harm reduction and treatment interventions. Would it be much trouble to add a concept to your nightly NLP runs that would be a search for specific standard text (e.g. "Pt on DOD OUD report assessed. Pt does not meet criteria for opioid use disorder.") in clinical notes? We could even share the patients that it could potentially be documented on if that would be helpful. We would then use positives on that text search as exclusion criteria to remove patients from the case management program on the special report in STORM. Tolessa is already aware of the plan, if we can make the NLP side work. If that is doable, I can finalize the exact text with the national case manager. I note that it isn't a lot of patients and the national care manager is in contact with their providers, so he can talk them through the documentation.

@suzytamang<https://github.com/suzytamang> Please let me know if the following proposed fix would be appropriate. I'm somewhat worried that the modifiers might interfere w/ pulling these mentions. Please advise.

  *    Add new dict.txt row w/ term "Pt on DOD OUD report assessed. Pt does not meet criteria for opioid use disorder." or whatever the final exact term, as specified by the national case manager, is determined to be. For example,
44000|Pt on DOD OUD report assessed. Pt does not meet criteria for opioid use disorder.|DODOUD|response1
  *    Add new DODOUD concept to step2.sh
  *    Add new DODOUD concept to step3.sh
  *    Add new DODOUD concept to step4.sh
  *    Add new DODOUD concept to step5.sh
  *    Add new DODOUD concept to neg_trigs.json
  *    Add new DODOUD concept to na_trigs.json

**Comment by suzytamang** [comment]
Hi Vilija,

Hi again,

I see you already figured a lot of this out!  Didn't see it at first.

For a change to the production env't for the purpose of V2.1 release deadline, I'd suggest:


  1.  adding the following new dictionary term to github repo

44000|PDOD OUD report|DODOUD|report

It does not sound like they know the specific text they need or how to identify it.  Unfortunately, we can't help them with that now, but we can help them get started on content analysis on their own.  What's above is all they need to begin their exploratory data work.  It will likely be sensitive and they can work on getting more specific for the next itteration.

It's still very early stage, but when Dax is able to put a work flow in place to support testing of any changes, we would also complete the following:


  1.
Add new DODOUD concept to step2.sh
  2.
Run code and do set of checks on output
  3.
Add new DODOUD concept to step3.sh
  4.
Run code and do set of checks on output
  5.
Add new DODOUD concept to step4.sh
  6.
Run code and set of checks on output
  7.
Add new DODOUD concept to step5.sh
  8.
Run code and do a new set of checks on output

And there is no need to add anything to the trigger files as they are not applicable.

Hope that was helpful!  Let me know if you have any questions.

Suzanne







________________________________

**Comment by suzytamang** [comment]
I saw an error.  It should be:   44000|DOD OUD report|DODOUD|report
________________________________

**Comment by vilijajoyce** [comment]
Tx @suzytamang - this is very helpful! Per your advice, I've asked Jodie/clinical lead to get back to me by Mon, 8/26/24 for inclusion in the CLEVER 2.1 release. @dax-westerman , copying you for your awareness.

**Comment by suzytamang** [comment]
Great!  But after reading Jodie's request more carefully, it sounds like they don't know how this language is documented in the notes and they don't have someone that can help them figure this out. They aren't familiar with how our pipeline how works either.  That makes it even more complicated to solicit good advice advice from them about "terms".  

I'd be happy to review whatever they sent to see what might be appropriate to include, but for now I suggest we move ahead with adding only "DOD OUD report".  That should tag a lot of potentially relevant to content for them that they can further refine through content analysis, possibly with help from Tolessa.  Then, they can propose additional updates, such as the PDMP folks did for a future round of updates, and after they have a better understanding of the pipeline and associated outputs.

**Comment by vilijajoyce** [comment]
> 1. Add new DODOUD concept to step2.sh 2. Run code and do set of checks on output 3. Add new DODOUD concept to step3.sh 4. Run code and do set of checks on output 5. Add new DODOUD concept to step4.sh 6. Run code and set of checks on output 7. Add new DODOUD concept to step5.sh 8. Run code and do a new set of checks on output

@dax-westerman I'm ready to take on this task as well as #37 , but could use your guidance re: Suzanne's request to run/check code in between each revision. TIA.

**Comment by vilijajoyce** [comment]
@suzytamang Concerns from Jodie via Teams - just thought I'd log them here too.
![image](https://github.com/user-attachments/assets/7918e060-71c7-4b63-8fb7-405ab1f04949)

**Comment by dax-westerman** [comment]
@vilijajoyce I'm still in a holding pattern for triggering the run, which limits testing, but I have some suggestions as it pertains to the workflow that should help work best here.  I will return to this issues with an update shortly.

**Comment by vilijajoyce** [comment]
Close #75
